<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" href="orders.xsl"?>
<!DOCTYPE orders [
<!ELEMENT orders (order)*>
<!ELEMENT order (name , price , quantity , waiter)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT waiter (#PCDATA)>
]>
<orders>
	<order>
		<name>Σοκολάτα</name>
		<price>4.00</price>
		<quantity>3</quantity>
		<waiter>Αντωνίου Εύα</waiter>
	</order>
	<order>
		<name>Σοκολάτα</name>
		<price>4.00</price>
		<quantity>3</quantity>
		<waiter>Αντωνίου Εύα</waiter>
	</order>
	<order>
		<name>Γάλα</name>
		<price>2.80</price>
		<quantity>2</quantity>
		<waiter>Αντωνίου Εύα</waiter>
	</order>
	<order>
		<name>Γάλα</name>
		<price>2.80</price>
		<quantity>2</quantity>
		<waiter>Αντωνίου Εύα</waiter>
	</order>
	<order>
		<name>Κονιάκ</name>
		<price>7.35</price>
		<quantity>2</quantity>
		<waiter>Αντωνίου Εύα</waiter>
	</order>
	<order>
		<name>Κονιάκ</name>
		<price>7.35</price>
		<quantity>2</quantity>
		<waiter>Αντωνίου Εύα</waiter>
	</order>
</orders>
